# -*- coding: utf-8 -*-
"""Matter_Precedent_Risk_Agents_SL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fVyD5vMkmxzeLrqYfNR9cg62NVMU30J
"""

import os
import json
import random
from typing import List, Dict, Any
from datetime import datetime

import streamlit as st
import aisuite
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from tavily import TavilyClient


MODEL_NAME = "openai:gpt-4o-mini"
random.seed(42)


@st.cache_resource
def get_client():
    """
    Lazily create the aisuite client AFTER the API key is set.
    Cached so we don't recreate it on every rerun.
    """
    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError("OPENAI_API_KEY is not set.")
    return aisuite.Client()


def get_tavily_client():
    if not os.getenv("TAVILY_API_KEY"):
        raise RuntimeError("TAVILY_API_KEY is not set.")
    return TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))


def llm_complete(system_prompt: str, user_prompt: str) -> str:
    """
    Small helper to call the model through aisuite.
    """
    client = get_client()
    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )
    return response.choices[0].message.content.strip()


# =========================================================
# SYNTHETIC INTERNAL DATA
# =========================================================

def generate_core_past_matters() -> List[Dict[str, Any]]:
    return [
        {
            "id": "M001",
            "practice_area": "Antitrust",
            "industry": "Technology",
            "client_type": "Public Company",
            "matter_summary": (
                "Technology platform company faced antitrust scrutiny over alleged exclusionary conduct, "
                "bundling practices, and market power in a core software ecosystem."
            ),
            "key_issues": [
                "market power",
                "bundling",
                "platform conduct",
                "behavioral remedies",
            ],
            "approach_taken": (
                "Defense focused on consumer benefit narrative, efficiency justification, "
                "and narrowing the relevant market definition."
            ),
            "outcome": "Investigation resolved through negotiated behavioral commitments.",
            "lessons_learned": (
                "Past precedent was helpful, but regulator posture had shifted more aggressively than expected."
            ),
        },
        {
            "id": "M002",
            "practice_area": "M&A",
            "industry": "Healthcare",
            "client_type": "Private Equity",
            "matter_summary": (
                "Private equity sponsor pursued acquisition of healthcare services company with significant "
                "regulatory and concentration concerns."
            ),
            "key_issues": [
                "deal timing",
                "regulatory review",
                "financing complexity",
                "market concentration",
            ],
            "approach_taken": (
                "Cross-practice coordination between M&A, antitrust, and finance teams; mitigation planning began early."
            ),
            "outcome": "Transaction approved after timeline extension and negotiated remedies.",
            "lessons_learned": (
                "The earlier the team modeled regulator objections, the stronger the negotiation position."
            ),
        },
        {
            "id": "M003",
            "practice_area": "White Collar / Regulatory",
            "industry": "Financial Services",
            "client_type": "Public Company",
            "matter_summary": (
                "Financial institution faced investigation tied to disclosure controls, compliance gaps, "
                "and executive-level oversight concerns."
            ),
            "key_issues": [
                "disclosure",
                "controls",
                "oversight",
                "investigation response",
            ],
            "approach_taken": (
                "Internal fact development, regulator engagement strategy, and remediation narrative built in parallel."
            ),
            "outcome": "Matter resolved with penalties lower than initial exposure estimates.",
            "lessons_learned": (
                "Consistency between factual record and remediation story was critical."
            ),
        },
        {
            "id": "M004",
            "practice_area": "Litigation",
            "industry": "Consumer Products",
            "client_type": "Public Company",
            "matter_summary": (
                "Company faced commercial litigation and follow-on reputational risk after allegations of deceptive practices."
            ),
            "key_issues": [
                "consumer harm theory",
                "damages framing",
                "reputation",
                "settlement posture",
            ],
            "approach_taken": (
                "Team split strategy across courtroom posture and parallel business messaging."
            ),
            "outcome": "Case settled before trial under confidential terms.",
            "lessons_learned": (
                "Reputational context mattered almost as much as legal merits."
            ),
        },
        {
            "id": "M005",
            "practice_area": "Antitrust",
            "industry": "Healthcare",
            "client_type": "Strategic Buyer",
            "matter_summary": (
                "Acquirer faced antitrust questions over a vertical integration involving healthcare data and services."
            ),
            "key_issues": [
                "vertical integration",
                "foreclosure theory",
                "data advantage",
                "regulatory challenge",
            ],
            "approach_taken": (
                "Emphasized pro-competitive benefits, interoperability, and lack of foreclosure incentives."
            ),
            "outcome": "Review was prolonged; transaction structure was modified.",
            "lessons_learned": (
                "Older transaction precedent did not cleanly map onto newer regulator concerns about data concentration."
            ),
        },
        {
            "id": "M006",
            "practice_area": "Activism Defense",
            "industry": "Industrials",
            "client_type": "Public Company",
            "matter_summary": (
                "Public company confronted activist pressure tied to governance, capital allocation, and strategic alternatives."
            ),
            "key_issues": [
                "board governance",
                "activist pressure",
                "public narrative",
                "shareholder communication",
            ],
            "approach_taken": (
                "Coordinated activism defense, governance review, and investor messaging."
            ),
            "outcome": "Campaign de-escalated after negotiated governance changes.",
            "lessons_learned": (
                "Speed and internal alignment were more important than legal complexity."
            ),
        },
        {
            "id": "M007",
            "practice_area": "Finance",
            "industry": "Technology",
            "client_type": "Private Equity",
            "matter_summary": (
                "Sponsor-backed financing required restructuring due to market volatility and covenant stress."
            ),
            "key_issues": [
                "liquidity",
                "covenants",
                "market volatility",
                "refinancing risk",
            ],
            "approach_taken": (
                "Debt restructuring workstream coordinated with sponsors, lenders, and transactional counsel."
            ),
            "outcome": "Refinancing completed with tighter economics.",
            "lessons_learned": (
                "Financial stress can quickly create adjacent restructuring and dispute risk."
            ),
        },
        {
            "id": "M008",
            "practice_area": "M&A",
            "industry": "Technology",
            "client_type": "Strategic Buyer",
            "matter_summary": (
                "Technology acquisition triggered extensive diligence around data practices, IP ownership, and integration risk."
            ),
            "key_issues": [
                "IP diligence",
                "data practices",
                "integration risk",
                "deal protections",
            ],
            "approach_taken": (
                "Built diligence escalation framework and negotiated targeted indemnity protections."
            ),
            "outcome": "Deal signed with enhanced protections and post-closing remediation obligations.",
            "lessons_learned": (
                "Operational diligence themes often become legal risk themes after signing."
            ),
        },
    ]


def generate_large_synthetic_dataset(n: int = 60) -> List[Dict[str, Any]]:
    practice_areas = [
        "Antitrust", "M&A", "Litigation", "White Collar / Regulatory",
        "Finance", "Activism Defense"
    ]
    industries = [
        "Technology", "Healthcare", "Financial Services",
        "Energy", "Consumer Products", "Industrials"
    ]
    client_types = [
        "Public Company", "Private Equity", "Strategic Buyer", "Financial Sponsor"
    ]

    issue_bank = {
        "Antitrust": ["market power", "bundling", "pricing practices", "vertical integration", "data concentration"],
        "M&A": ["deal timing", "regulatory review", "financing complexity", "integration risk", "diligence gaps"],
        "Litigation": ["damages exposure", "reputation", "settlement posture", "factual inconsistency", "procedural risk"],
        "White Collar / Regulatory": ["disclosure", "controls", "oversight", "investigation response", "remediation"],
        "Finance": ["liquidity", "covenants", "market volatility", "refinancing risk", "credit stress"],
        "Activism Defense": ["board governance", "shareholder communication", "capital allocation", "strategic alternatives", "public narrative"],
    }

    approach_templates = [
        "Cross-practice coordination was initiated early to align legal and business positioning.",
        "The team focused on narrowing the dispute frame and strengthening the factual narrative.",
        "Mitigation planning began early, with legal and commercial workstreams coordinated in parallel.",
        "The strategy emphasized consistency between regulator-facing and business-facing narratives.",
        "The team paired substantive defense arguments with contingency planning around remedies or restructuring.",
    ]

    outcome_templates = [
        "Matter resolved through negotiated settlement.",
        "Review was prolonged and ultimately required structural changes.",
        "Transaction proceeded after additional diligence and revised protections.",
        "Investigation closed with lower-than-expected penalties.",
        "Dispute de-escalated after coordinated legal and business response.",
    ]

    lesson_templates = [
        "Older precedent was useful, but only after adjusting for changed regulator posture.",
        "Cross-practice coordination materially improved response quality.",
        "Initial precedent matches overstated similarity and had to be narrowed.",
        "Commercial context was as important as legal theory.",
        "The strongest reusable lesson was process discipline rather than substantive precedent alone.",
    ]

    rows = []
    for i in range(1, n + 1):
        practice = random.choice(practice_areas)
        industry = random.choice(industries)
        client_type = random.choice(client_types)
        issues = random.sample(issue_bank[practice], k=3)

        rows.append({
            "id": f"S{i:03d}",
            "practice_area": practice,
            "industry": industry,
            "client_type": client_type,
            "matter_summary": (
                f"{client_type} in {industry} faced a {practice.lower()}-related matter "
                f"involving {issues[0]}, {issues[1]}, and {issues[2]}."
            ),
            "key_issues": issues,
            "approach_taken": random.choice(approach_templates),
            "outcome": random.choice(outcome_templates),
            "lessons_learned": random.choice(lesson_templates),
        })

    return rows


# =========================================================
# RETRIEVAL
# =========================================================

def matter_to_text(m: Dict[str, Any]) -> str:
    return " | ".join([
        m.get("practice_area", ""),
        m.get("industry", ""),
        m.get("client_type", ""),
        m.get("matter_summary", ""),
        " ".join(m.get("key_issues", [])),
        m.get("approach_taken", ""),
        m.get("outcome", ""),
        m.get("lessons_learned", ""),
    ])


def retrieve_similar_matters(
    new_matter: Dict[str, Any],
    past_matters: List[Dict[str, Any]],
    top_k: int = 3,
    min_similarity: float = 0.05,
) -> List[Dict[str, Any]]:
    query_text = " | ".join([
        new_matter.get("practice_area", ""),
        new_matter.get("industry", ""),
        new_matter.get("client_type", ""),
        new_matter.get("matter_summary", ""),
        " ".join(new_matter.get("key_issues", [])),
    ])

    corpus = [matter_to_text(m) for m in past_matters]
    vectorizer = TfidfVectorizer(stop_words="english")
    X = vectorizer.fit_transform(corpus + [query_text])

    sims = cosine_similarity(X[-1], X[:-1]).flatten()
    ranked_idx = sims.argsort()[::-1]

    results = []
    for idx in ranked_idx:
        if sims[idx] < min_similarity:
            continue
        item = dict(past_matters[idx])
        item["similarity_score"] = float(sims[idx])
        results.append(item)
        if len(results) >= top_k:
            break
    return results


def format_internal_precedents(similar_matters: List[Dict[str, Any]]) -> str:
    if not similar_matters:
        return "No strong internal precedents found."

    chunks = []
    for i, m in enumerate(similar_matters, start=1):
        chunks.append(
            f"""[Internal Precedent {i}]
ID: {m["id"]}
Practice Area: {m["practice_area"]}
Industry: {m["industry"]}
Client Type: {m["client_type"]}
Similarity Score: {m["similarity_score"]:.3f}
Matter Summary: {m["matter_summary"]}
Key Issues: {", ".join(m["key_issues"])}
Approach Taken: {m["approach_taken"]}
Outcome: {m["outcome"]}
Lessons Learned: {m["lessons_learned"]}
"""
        )
    return "\n\n".join(chunks)


# =========================================================
# TAVILY
# =========================================================

RELEVANCE_TERMS = {
    "antitrust", "doj", "ftc", "regulator", "regulatory", "bundling",
    "platform", "market power", "monopoly", "competition", "remedies",
    "structural", "behavioral", "enforcement", "lawsuit", "investigation"
}

NOISY_DOMAINS = {
    "itnews.com.au",
    "thenextweb.com",
    "ecologist.org",
}

NOISY_TITLE_PATTERNS = [
    "in pictures",
    "summit",
    "sentiment is waning",
    "children’s social media use",
]


def generate_tavily_queries(new_matter: Dict[str, Any]) -> List[str]:
    practice = (new_matter.get("practice_area") or "").lower()
    industry = (new_matter.get("industry") or "").lower()

    if practice == "antitrust" and industry == "technology":
        return [
            "DOJ FTC antitrust tech platform bundling recent",
            "recent antitrust enforcement platform control technology 2025 2026",
            "behavioral remedies versus structural remedies antitrust tech platforms recent",
        ]

    issues = [x.lower() for x in new_matter.get("key_issues", [])]
    key1 = issues[0] if len(issues) > 0 else "core issue"
    key2 = issues[1] if len(issues) > 1 else "regulatory posture"

    return [
        f"recent {practice} {industry} {key1} enforcement",
        f"recent {practice} regulator posture {key2}",
        f"{practice} external developments affecting precedent reliability recent",
    ]


def relevance_score(title: str, summary: str, query: str) -> int:
    text = f"{title} {summary} {query}".lower()
    score = 0

    for term in RELEVANCE_TERMS:
        if term in text:
            score += 1

    for boost in ["doj", "ftc", "antitrust", "platform", "bundling", "remedies"]:
        if boost in text:
            score += 2

    return score


def is_noisy_result(title: str, url: str) -> bool:
    title_l = (title or "").lower()
    url_l = (url or "").lower()

    if any(domain in url_l for domain in NOISY_DOMAINS):
        return True

    if any(pattern in title_l for pattern in NOISY_TITLE_PATTERNS):
        return True

    return False


def tavily_search_packet(queries: List[str], max_results: int = 5) -> Dict[str, Any]:
    client = get_tavily_client()
    items = []

    for q in queries:
        try:
            result = client.search(
                query=q,
                search_depth="advanced",
                topic="news",
                max_results=max_results,
                include_answer=True,
                include_raw_content=False,
            )

            answer = (result.get("answer") or "").strip()
            if answer:
                items.append({
                    "kind": "answer",
                    "query": q,
                    "title": f"Tavily answer for: {q}",
                    "url": "",
                    "summary": answer,
                    "score": relevance_score(f"Tavily answer for: {q}", answer, q),
                })

            for r in result.get("results", []):
                title = (r.get("title") or "").strip()
                url = (r.get("url") or "").strip()
                summary = (r.get("content") or "").strip()

                if is_noisy_result(title, url):
                    continue

                score = relevance_score(title, summary, q)
                if score < 3:
                    continue

                items.append({
                    "kind": "result",
                    "query": q,
                    "title": title or "Untitled",
                    "url": url,
                    "summary": summary[:900],
                    "score": score,
                })

        except Exception as e:
            items.append({
                "kind": "error",
                "query": q,
                "title": "Tavily error",
                "url": "",
                "summary": f"Search failed: {e}",
                "score": 0,
            })

    deduped = []
    seen = set()
    for item in sorted(items, key=lambda x: x.get("score", 0), reverse=True):
        key = (item.get("url") or item.get("title") or "").strip().lower()
        if not key:
            continue
        if key in seen:
            continue
        seen.add(key)
        deduped.append(item)

    return {"queries": queries, "items": deduped}


def format_external_context(packet: Dict[str, Any], max_items: int = 4) -> str:
    usable = [
        x for x in packet.get("items", [])
        if x.get("kind") in {"answer", "result"}
    ][:max_items]

    if not usable:
        return "No strong external public context retrieved."

    chunks = []
    for i, item in enumerate(usable, start=1):
        chunks.append(
            f"""[External Context {i}]
Query: {item.get("query", "")}
Title: {item.get("title", "")}
URL: {item.get("url", "")}
Relevance Score: {item.get("score", 0)}
Summary: {item.get("summary", "")}
"""
        )
    return "\n\n".join(chunks)


def format_external_sources(packet: Dict[str, Any], max_items: int = 8) -> str:
    rows = [
        x for x in packet.get("items", [])
        if x.get("kind") == "result"
    ][:max_items]

    if not rows:
        return "No strong public sources."

    return "\n".join(
        f"- {r['title']} | {r['url']} | score={r.get('score', 0)} | query={r['query']}"
        for r in rows
    )


# =========================================================
# AGENTS
# =========================================================

AGENTS = [
    {
        "name": "Precedent Advocate",
        "system": (
            "You are a senior partner arguing that prior firm matters provide a reliable playbook "
            "for the current situation. You strongly believe in precedent as a guide to strategy."
        ),
        "instructions": (
            "Make a confident argument for why internal precedent applies.\n"
            "- Use exactly ONE internal precedent as your anchor\n"
            "- Name one reusable tactic or lesson\n"
            "- Explain why it fits this matter\n"
            "- Focus on what the team should actively reuse\n"
            "- Avoid discussing external context unless needed for contrast"
        ),
        "turn_format": (
            "Output exactly 3 bullets:\n"
            "1. Anchor precedent\n"
            "2. Why it applies\n"
            "3. Reusable tactic"
        ),
    },
    {
        "name": "Skeptic / Challenger",
        "system": (
            "You are a critical reviewer whose job is to prevent the team from relying on misleading precedent. "
            "You assume most analogies are only partially valid."
        ),
        "instructions": (
            "Challenge the strongest precedent argument.\n"
            "- Identify exactly TWO reasons the analogy weakens or breaks\n"
            "- Focus on mismatch in facts, structure, posture, or risk profile\n"
            "- Do not simply say regulators are tougher now unless tied to a concrete mismatch\n"
            "- Your job is to show where the analogy stops working"
        ),
        "turn_format": (
            "Output exactly 3 bullets:\n"
            "1. Main flaw in analogy\n"
            "2. Secondary flaw\n"
            "3. Risk of relying on it"
        ),
    },
    {
        "name": "External Context Agent",
        "system": (
            "You are responsible for grounding the discussion in real-world developments. "
            "You use external signals to determine whether internal precedent is still valid."
        ),
        "instructions": (
            "Use external public context to test precedent.\n"
            "- Cite exactly ONE concrete external development, case, or pattern\n"
            "- Explain what it changes for this matter\n"
            "- State whether it strengthens, weakens, or creates mixed evidence for reliance on precedent\n"
            "- If the external sources are only weakly relevant, say that explicitly and lower your confidence\n"
            "- If the external signal supports the precedent, say it strengthens it\n"
            "- If the external signal is mixed, say the evidence is mixed\n"
            "- Do not claim the precedent is weakened unless the external context clearly cuts against it\n"
            "- Do not overstate weak evidence"
        ),
        "turn_format": (
            "Output exactly 3 bullets:\n"
            "1. External signal\n"
            "2. What it changes\n"
            "3. Conclusion for precedent reliability"
        ),
    },
    {
        "name": "Blind Spot Detector",
        "system": (
            "You are responsible for identifying what the team is missing. "
            "You assume both precedent and external context may be incomplete."
        ),
        "instructions": (
            "Identify exactly ONE important blind spot.\n"
            "- It must be something not already covered by the other agents\n"
            "- Explain why it matters for decision-making\n"
            "- State what the team should test or clarify next"
        ),
        "turn_format": (
            "Output exactly 3 bullets:\n"
            "1. Blind spot\n"
            "2. Why it matters\n"
            "3. What the team needs to test"
        ),
    },
    {
        "name": "Synthesizer",
        "system": (
            "You are a senior decision-maker responsible for turning conflicting views into a clear, actionable position."
        ),
        "instructions": (
            "Make a call.\n"
            "- State what precedent is still usable\n"
            "- State what the team should NOT assume\n"
            "- Give exactly TWO legal workstream actions\n"
            "- Use law-firm practical language: prepare, pressure-test, develop, model, engage, preserve\n"
            "- Do not summarize the room; decide"
        ),
        "turn_format": (
            "Output exactly 4 bullets:\n"
            "1. What still holds\n"
            "2. What not to assume\n"
            "3. Action 1\n"
            "4. Action 2"
        ),
    },
]


def run_agent_turn(
    agent: Dict[str, str],
    new_matter: Dict[str, Any],
    internal_context: str,
    external_context: str,
    prior_discussion: str,
    round_num: int,
) -> str:
    prompt = f"""
You are acting as [{agent["name"]}] in a precedent stress-test session.

Your role:
{agent["instructions"]}

Required output format:
{agent["turn_format"]}

Current matter:
{json.dumps(new_matter, indent=2)}

Retrieved internal precedents:
INTERNAL_START
{internal_context}
INTERNAL_END

Retrieved external public context:
EXTERNAL_START
{external_context}
EXTERNAL_END

Prior discussion:
DISCUSSION_START
{prior_discussion if prior_discussion.strip() else "(none yet)"}
DISCUSSION_END

Current round:
{round_num}

Rules:
- Be specific, not generic
- Do not invent facts
- Do not repeat prior points unless directly refining or challenging them
- Start exactly with "[{agent['name']}]:"
- Output only your answer
"""
    out = llm_complete(agent["system"], prompt)
    if not out.startswith(f"[{agent['name']}]"):
        out = f"[{agent['name']}]: {out}"
    return out


def run_debate(
    new_matter: Dict[str, Any],
    internal_context: str,
    external_context: str,
    rounds: int = 1,
) -> str:
    transcript = []
    for round_num in range(1, rounds + 1):
        for agent in AGENTS:
            prior = "\n".join(transcript[-10:]) if transcript else ""
            turn = run_agent_turn(
                agent=agent,
                new_matter=new_matter,
                internal_context=internal_context,
                external_context=external_context,
                prior_discussion=prior,
                round_num=round_num,
            )
            transcript.append(turn)
    return "\n\n".join(transcript)


def build_final_report(
    new_matter: Dict[str, Any],
    internal_context: str,
    external_context: str,
    discussion: str,
) -> str:
    prompt = f"""
You are preparing a final memo for a law firm team using an internal precedent stress-test system.

Current matter:
{json.dumps(new_matter, indent=2)}

Internal precedents:
{internal_context}

External context:
{external_context}

Debate transcript:
{discussion}

Write a concise memo in Markdown with exactly these sections:

# Final Precedent Stress-Test Memo

## 1. Best Internal Analogy
## 2. Where That Analogy Breaks
## 3. External Development That Matters Most
## 4. Reusable Lesson
## 5. What The Team Should Do Now
## 6. Confidence

Requirements:
- Be concrete and comparative
- Explicitly name the best precedent by ID if one exists
- Explicitly state one thing the team should reuse
- Explicitly state one thing the team should not assume
- Under "What The Team Should Do Now", provide exactly 3 numbered actions
- Write like a sharp internal strategy note, not a generic AI summary
- Use law-firm practical language
- Prefer language like: develop, preserve, pressure-test, prepare fallback positions, engage early, refine arguments
"""
    return llm_complete(
        "You write sharp, partner-ready internal legal strategy memos.",
        prompt
    )


def run_pipeline_from_matter(
    new_matter: Dict[str, Any],
    rounds: int = 1,
    synthetic_n: int = 40,
    top_k: int = 3,
    min_similarity: float = 0.05,
    tavily_max_results: int = 5,
    external_context_items: int = 4,
):
    core_matters = generate_core_past_matters()
    synthetic_matters = generate_large_synthetic_dataset(n=synthetic_n)
    past_matters = core_matters + synthetic_matters

    similar = retrieve_similar_matters(
        new_matter=new_matter,
        past_matters=past_matters,
        top_k=top_k,
        min_similarity=min_similarity,
    )
    internal_context = format_internal_precedents(similar)

    queries = generate_tavily_queries(new_matter)
    tavily_packet = tavily_search_packet(queries, max_results=tavily_max_results)
    external_context = format_external_context(tavily_packet, max_items=external_context_items)

    discussion = run_debate(
        new_matter=new_matter,
        internal_context=internal_context,
        external_context=external_context,
        rounds=rounds,
    )

    final_report = build_final_report(
        new_matter=new_matter,
        internal_context=internal_context,
        external_context=external_context,
        discussion=discussion,
    )

    full_output = f"""# Final Precedent Stress-Test Output

## Current Matter
{json.dumps(new_matter, indent=2)}

## Retrieved Internal Precedents
{internal_context}

## Tavily Queries
{json.dumps(queries, indent=2)}

## Tavily Sources
{format_external_sources(tavily_packet)}

## Multi-Agent Debate
{discussion}

## Final Memo
{final_report}
"""

    return discussion, final_report, full_output, internal_context, queries, tavily_packet, external_context, similar


def extract_matter_from_text(memo_text: str, deal_name: str) -> Dict[str, Any]:
    prompt = f"""
You are reading a memo and converting it into a structured matter JSON.

Deal or matter name:
{deal_name}

Memo text:
MEMO_START
{memo_text[:12000]}
MEMO_END

Return valid JSON only with exactly these keys:
matter_name
practice_area
industry
client_type
matter_summary
key_issues

Rules:
- key_issues must be a JSON array of short strings
- infer missing values conservatively
- if unsure, choose the closest reasonable label
- practice_area must be one of:
  Antitrust, M&A, Litigation, White Collar / Regulatory, Finance, Activism Defense
- industry must be one of:
  Technology, Healthcare, Financial Services, Energy, Consumer Products, Industrials
- client_type must be one of:
  Public Company, Private Equity, Strategic Buyer, Financial Sponsor
"""
    out = llm_complete(
        "You extract structured legal matter metadata from memo text.",
        prompt
    )

    try:
        return json.loads(out)
    except Exception:
        return {
            "matter_name": deal_name or "Uploaded Matter",
            "practice_area": "Antitrust",
            "industry": "Technology",
            "client_type": "Public Company",
            "matter_summary": memo_text[:1000],
            "key_issues": ["bundling", "market power", "regulatory scrutiny"],
        }


st.set_page_config(page_title="IC Shadow Agents", page_icon="📊", layout="wide")
st.title("IC Shadow Agents – Shadow Investment Committee Simulator")

st.info(
    "Upload or paste an IC memo, set the deal name and number of rounds, and generate a multi-role Shadow IC debate plus a structured challenge checklist."
)

if "discussion" not in st.session_state:
    st.session_state.discussion = None
if "final_report" not in st.session_state:
    st.session_state.final_report = None
if "full_output" not in st.session_state:
    st.session_state.full_output = None
if "internal_context" not in st.session_state:
    st.session_state.internal_context = None
if "queries" not in st.session_state:
    st.session_state.queries = None
if "external_context" not in st.session_state:
    st.session_state.external_context = None
if "similar" not in st.session_state:
    st.session_state.similar = None
if "tavily_packet" not in st.session_state:
    st.session_state.tavily_packet = None

api_key = st.text_input(
    "OpenAI API Key",
    type="password",
    value=os.getenv("OPENAI_API_KEY", ""),
    help="Your OpenAI-compatible key used by aisuite.",
)

tavily_key = st.text_input(
    "Tavily API Key",
    type="password",
    value=os.getenv("TAVILY_API_KEY", ""),
    help="Your Tavily API key.",
)

if api_key:
    os.environ["OPENAI_API_KEY"] = api_key
if tavily_key:
    os.environ["TAVILY_API_KEY"] = tavily_key

col_left, col_right = st.columns([2, 1])

with col_right:
    deal_name = st.text_input("Deal Name (alias)", value="Acme Industries")
    rounds = st.slider("Number of Debate Rounds", min_value=1, max_value=4, value=2, step=1)

    memo_mode = st.radio(
        "How do you want to provide the IC memo?",
        ["Upload .md/.txt file", "Paste memo text"],
        index=0,
    )

with col_left:
    uploaded_file = None
    memo_text_input = ""

    if memo_mode == "Upload .md/.txt file":
        uploaded_file = st.file_uploader(
            "Upload IC memo file",
            type=["md", "txt"],
            help="Markdown or plain-text IC memo.",
        )
    else:
        memo_text_input = st.text_area(
            "Paste IC memo text",
            height=300,
            placeholder="Paste the full Investment Committee memo here...",
        )

run_button = st.button("Run Shadow IC")

if run_button:
    if not api_key:
        st.warning("Please enter your OpenAI API Key before running.")
    elif not tavily_key:
        st.warning("Please enter your Tavily API Key before running.")
    else:
        if memo_mode == "Upload .md/.txt file":
            if not uploaded_file:
                st.warning("Please upload a memo file or switch to paste mode.")
                memo_text = ""
            else:
                try:
                    memo_text = uploaded_file.read().decode("utf-8")
                except Exception as e:
                    st.error(f"Could not read uploaded file: {e}")
                    memo_text = ""
        else:
            memo_text = memo_text_input

        if memo_text and memo_text.strip():
            try:
                with st.spinner("Extracting matter and running precedent stress-test..."):
                    new_matter = extract_matter_from_text(memo_text, deal_name)

                    (
                        discussion,
                        final_report,
                        full_output,
                        internal_context,
                        queries,
                        tavily_packet,
                        external_context,
                        similar,
                    ) = run_pipeline_from_matter(
                        new_matter=new_matter,
                        rounds=rounds,
                    )

                st.session_state.discussion = discussion
                st.session_state.final_report = final_report
                st.session_state.full_output = full_output
                st.session_state.internal_context = internal_context
                st.session_state.queries = queries
                st.session_state.tavily_packet = tavily_packet
                st.session_state.external_context = external_context
                st.session_state.similar = similar

                st.success("Run completed.")
            except Exception as e:
                st.error(f"Error while running the app: {e}")
        else:
            st.warning("Memo is empty. Please upload a file or paste memo text.")

if st.session_state.discussion or st.session_state.final_report:
    st.subheader("Extracted / Structured Matter")
    if st.session_state.full_output:
        # parsed from saved output is not necessary; just showing result blocks below
        pass

    st.subheader("Retrieved Internal Precedents")
    if st.session_state.internal_context:
        st.text(st.session_state.internal_context)

    st.subheader("Tavily Queries")
    if st.session_state.queries:
        st.json(st.session_state.queries)

    st.subheader("Tavily Sources")
    if st.session_state.tavily_packet:
        st.text(format_external_sources(st.session_state.tavily_packet))

    st.subheader("External Context")
    if st.session_state.external_context:
        st.text(st.session_state.external_context)

    st.subheader("Multi-Agent Debate")
    if st.session_state.discussion:
        st.text(st.session_state.discussion)

    st.subheader("Final Precedent Stress-Test Memo")
    if st.session_state.final_report:
        st.markdown(st.session_state.final_report)

    if st.session_state.full_output:
        default_filename = f"{(deal_name or 'Deal').replace(' ', '_')}_PrecedentStressTest_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.md"
        st.download_button(
            "Download full output (Markdown)",
            data=st.session_state.full_output,
            file_name=default_filename,
            mime="text/markdown",
        )